theme: jekyll-theme-minimal
description: |
  <img src="img/moxsoar_logo_bg.svg" width="150"><br>

  Navigation<br>
    <a href="getting_started.md">Overview</a><br>
    <a href="getting_started.md">Getting Started</a><br>
    <a href="authoring.md">Customization</a><br>
    <a href="pack_vcs.md">Version Control</a><br>
