theme: jekyll-theme-minimal
description: |
  Navigation
    <a href="getting_started.md">Getting Started</a>
    <a href="authoring.md">Customization</a>
    <a href="pack_vcs.md">Version Control</a>
