theme: jekyll-theme-minimal
description: |
  <img src="img/moxsoar_logo_bg.svg" width="150"><br>

  Navigation<br>
    <a href="index">Overview</a><br>
    <a href="getting_started">Getting Started</a><br>
    <a href="user_interface">Creating Content</a><br>
    <a href="authoring">Advanced</a><br>
    <a href="elasticsearch">Request Logging/Elasticsearch</a><br>
    <a href="pack_vcs">Version Control</a><br>
